version: '3.8'
services:
  web:
    image: nginx:alpine
    command: /bin/sh -c "echo '<h1>Teste Dokploy, Github e CS! Rafael Moreira</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - dokploy-network
    deploy:
  <Step title="Aplicar o deploy" subtitle="1 min">
    Clique no botão **Deploy** para atualizar as instâncias.
    * **Como verificar:** Execute `docker ps --filter name=rafael2` no terminal para verificar se novas instâncias foram distribuídas.
  </Step>
    replicas: 2
    placement:
      constraints:
        - node.role != none

networks:
  dokploy-network:
    external: true
