version: '3.8'
services:
  web:
    image: nginx:alpine
    command: /bin/sh -c "echo '<h1>Oi mundo! Rafael Moreira</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
